# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# A list of advisory IDs to ignore
ignore = [
    # These advisories are for unmaintained crates that don't have good alternatives
    # in the Rust ecosystem yet. We're monitoring them for updates.
    "RUSTSEC-2024-0320",  # yaml-rust is unmaintained
]

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "BSD-2-Clause",
    "Unicode-3.0",
    "ISC",
    "MPL-2.0",
    "Zlib",
    "CDLA-Permissive-2.0",
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"

[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "deny"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "deny"