services:
  adminer:
    image: adminer
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    ports:
      - ${ADMINER_PORT:-18080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-user}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-password}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-dracula}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-tables-filter tinymce}
