# Security configuration for Ledger Banking Rust

[advisories]
# Vulnerability aliases to ignore (if any)
ignore = []

[licenses]
# License checking
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
    "MPL-2.0",  # For some Mozilla libraries
]

[bans]
# Duplicate dependency checking
multiple-versions = "warn"
wildcards = "allow"

[sources]
# Allow only trusted sources
unknown-registry = "deny"
unknown-git = "deny"