use super::reason_and_purpose::*;
use banking_api::domain::{ReasonCategory, ReasonContext, ReasonSeverity};
use chrono::Utc;
use heapless::{String as HeaplessString, Vec as HeaplessVec};
use uuid::Uuid;

/// Common reason codes that should be seeded in the database
pub struct ReasonSeeds;

impl ReasonSeeds {
    pub fn get_initial_reasons() -> Vec<ReasonAndPurpose> {
        vec![
            // Loan Purposes
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("LOAN_PURPOSE_HOME_PURCHASE").unwrap(),
                category: ReasonCategory::LoanPurpose,
                context: ReasonContext::Loan,
                l1_content: Some(HeaplessString::try_from("Home Purchase").unwrap()),
                l2_content: Some(HeaplessString::try_from("Achat de Maison").unwrap()),
                l3_content: Some(HeaplessString::try_from("Kununua Nyumba").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: None,
                display_order: 1,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("LOAN_PURPOSE_BUSINESS_EXPANSION").unwrap(),
                category: ReasonCategory::LoanPurpose,
                context: ReasonContext::Loan,
                l1_content: Some(HeaplessString::try_from("Business Expansion").unwrap()),
                l2_content: Some(HeaplessString::try_from("Expansion d'Entreprise").unwrap()),
                l3_content: Some(HeaplessString::try_from("Upanuzi wa Biashara").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: None,
                display_order: 2,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("LOAN_PURPOSE_EDUCATION").unwrap(),
                category: ReasonCategory::LoanPurpose,
                context: ReasonContext::Loan,
                l1_content: Some(HeaplessString::try_from("Education").unwrap()),
                l2_content: Some(HeaplessString::try_from("Éducation").unwrap()),
                l3_content: Some(HeaplessString::try_from("Elimu").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: None,
                display_order: 3,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            // Account Closure Reasons
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("CLOSURE_CUSTOMER_REQUEST").unwrap(),
                category: ReasonCategory::AccountClosure,
                context: ReasonContext::Account,
                l1_content: Some(HeaplessString::try_from("Customer Request").unwrap()),
                l2_content: Some(HeaplessString::try_from("Demande du Client").unwrap()),
                l3_content: Some(HeaplessString::try_from("Ombi la Mteja").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::Low),
                display_order: 1,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("CLOSURE_INACTIVITY").unwrap(),
                category: ReasonCategory::AccountClosure,
                context: ReasonContext::Account,
                l1_content: Some(HeaplessString::try_from("Account Inactivity").unwrap()),
                l2_content: Some(HeaplessString::try_from("Inactivité du Compte").unwrap()),
                l3_content: Some(HeaplessString::try_from("Kutotumika kwa Akaunti").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: Some(ReasonSeverity::Low),
                display_order: 2,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("CLOSURE_COMPLIANCE_ISSUE").unwrap(),
                category: ReasonCategory::AccountClosure,
                context: ReasonContext::Account,
                l1_content: Some(HeaplessString::try_from("Compliance Issue").unwrap()),
                l2_content: Some(HeaplessString::try_from("Problème de Conformité").unwrap()),
                l3_content: Some(HeaplessString::try_from("Suala la Utiifu").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::High),
                display_order: 3,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("COMP-01").unwrap()),
                    reportable: true,
                    requires_sar: false,
                    requires_ctr: false,
                    retention_years: 7,
                    escalation_required: true,
                    risk_score_impact: Some(50),
                    no_tipping_off: false,
                    jurisdictions: HeaplessVec::new(),
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            // AML/CTF Reasons
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("AML_SUSPICIOUS_PATTERN").unwrap(),
                category: ReasonCategory::AmlAlert,
                context: ReasonContext::AmlCtf,
                l1_content: Some(HeaplessString::try_from("Suspicious transaction pattern detected").unwrap()),
                l2_content: Some(HeaplessString::try_from("Modèle de transaction suspect détecté").unwrap()),
                l3_content: Some(HeaplessString::try_from("Mfumo wa shughuli za kutiliwa shaka umegundulika").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::High),
                display_order: 1,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("FATF-R.16").unwrap()),
                    reportable: true,
                    requires_sar: true,
                    requires_ctr: false,
                    retention_years: 7,
                    escalation_required: true,
                    risk_score_impact: Some(25),
                    no_tipping_off: true,
                    jurisdictions: {
                        let mut vec = HeaplessVec::new();
                        vec.push(*b"CM").unwrap();
                        vec
                    },
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("CTF_SANCTIONS_MATCH").unwrap(),
                category: ReasonCategory::SanctionsHit,
                context: ReasonContext::AmlCtf,
                l1_content: Some(HeaplessString::try_from("Name matches sanctions list").unwrap()),
                l2_content: Some(HeaplessString::try_from("Le nom correspond à la liste des sanctions").unwrap()),
                l3_content: Some(HeaplessString::try_from("Jina linafanana na orodha ya vikwazo").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::Critical),
                display_order: 1,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("UN-RES-1267").unwrap()),
                    reportable: true,
                    requires_sar: true,
                    requires_ctr: false,
                    retention_years: 10,
                    escalation_required: true,
                    risk_score_impact: Some(100),
                    no_tipping_off: true,
                    jurisdictions: {
                        let mut vec = HeaplessVec::new();
                        vec.push(*b"CM").unwrap();
                        vec.push(*b"US").unwrap();
                        vec.push(*b"EU").unwrap();
                        vec
                    },
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("AML_HIGH_RISK_COUNTRY").unwrap(),
                category: ReasonCategory::HighRiskCountry,
                context: ReasonContext::AmlCtf,
                l1_content: Some(HeaplessString::try_from("Transaction involves high-risk jurisdiction").unwrap()),
                l2_content: Some(HeaplessString::try_from("Transaction implique une juridiction à haut risque").unwrap()),
                l3_content: Some(HeaplessString::try_from("Muamala unahusisha eneo lenye hatari kubwa").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::High),
                display_order: 2,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("FATF-HIGH-RISK").unwrap()),
                    reportable: true,
                    requires_sar: false,
                    requires_ctr: false,
                    retention_years: 7,
                    escalation_required: false,
                    risk_score_impact: Some(40),
                    no_tipping_off: false,
                    jurisdictions: HeaplessVec::new(),
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            // KYC Reasons
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("KYC_ID_EXPIRED").unwrap(),
                category: ReasonCategory::KycMissingDocument,
                context: ReasonContext::Kyc,
                l1_content: Some(HeaplessString::try_from("National ID has expired").unwrap()),
                l2_content: Some(HeaplessString::try_from("La carte d'identité nationale a expiré").unwrap()),
                l3_content: Some(HeaplessString::try_from("Kitambulisho cha taifa kimepita muda").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: Some(ReasonSeverity::Medium),
                display_order: 1,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("KYC-DOC-01").unwrap()),
                    reportable: false,
                    requires_sar: false,
                    requires_ctr: false,
                    retention_years: 5,
                    escalation_required: false,
                    risk_score_impact: Some(10),
                    no_tipping_off: false,
                    jurisdictions: HeaplessVec::new(),
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("KYC_PROOF_OF_ADDRESS_MISSING").unwrap(),
                category: ReasonCategory::KycMissingDocument,
                context: ReasonContext::Kyc,
                l1_content: Some(HeaplessString::try_from("Proof of address document required").unwrap()),
                l2_content: Some(HeaplessString::try_from("Justificatif de domicile requis").unwrap()),
                l3_content: Some(HeaplessString::try_from("Uthibitisho wa makazi unahitajika").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: Some(ReasonSeverity::Medium),
                display_order: 2,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("KYC-DOC-02").unwrap()),
                    reportable: false,
                    requires_sar: false,
                    requires_ctr: false,
                    retention_years: 5,
                    escalation_required: false,
                    risk_score_impact: Some(10),
                    no_tipping_off: false,
                    jurisdictions: HeaplessVec::new(),
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("KYC_SOURCE_OF_FUNDS_UNCLEAR").unwrap(),
                category: ReasonCategory::SourceOfFundsRequired,
                context: ReasonContext::Kyc,
                l1_content: Some(HeaplessString::try_from("Source of funds documentation required").unwrap()),
                l2_content: Some(HeaplessString::try_from("Documentation sur l'origine des fonds requise").unwrap()),
                l3_content: Some(HeaplessString::try_from("Hati za chanzo cha fedha zinahitajika").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::High),
                display_order: 1,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("KYC-SOF-01").unwrap()),
                    reportable: true,
                    requires_sar: false,
                    requires_ctr: false,
                    retention_years: 7,
                    escalation_required: true,
                    risk_score_impact: Some(30),
                    no_tipping_off: false,
                    jurisdictions: HeaplessVec::new(),
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            // Transaction Hold Reasons
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("HOLD_INSUFFICIENT_FUNDS").unwrap(),
                category: ReasonCategory::HoldReason,
                context: ReasonContext::Transaction,
                l1_content: Some(HeaplessString::try_from("Insufficient funds").unwrap()),
                l2_content: Some(HeaplessString::try_from("Fonds insuffisants").unwrap()),
                l3_content: Some(HeaplessString::try_from("Fedha hazitoshi").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: Some(ReasonSeverity::Medium),
                display_order: 1,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("HOLD_FRAUD_INVESTIGATION").unwrap(),
                category: ReasonCategory::HoldReason,
                context: ReasonContext::Transaction,
                l1_content: Some(HeaplessString::try_from("Under fraud investigation").unwrap()),
                l2_content: Some(HeaplessString::try_from("Enquête de fraude en cours").unwrap()),
                l3_content: Some(HeaplessString::try_from("Kuna uchunguzi wa udanganyifu").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: true,
                is_active: true,
                severity: Some(ReasonSeverity::High),
                display_order: 2,
                compliance_metadata: Some(ComplianceMetadata {
                    regulatory_code: Some(HeaplessString::try_from("FRAUD-01").unwrap()),
                    reportable: true,
                    requires_sar: false,
                    requires_ctr: false,
                    retention_years: 7,
                    escalation_required: true,
                    risk_score_impact: Some(75),
                    no_tipping_off: true,
                    jurisdictions: HeaplessVec::new(),
                }),
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
            
            // System Generated Reasons
            ReasonAndPurpose {
                id: Uuid::new_v4(),
                code: HeaplessString::try_from("SYSTEM_AUTO_DORMANCY").unwrap(),
                category: ReasonCategory::SystemGenerated,
                context: ReasonContext::System,
                l1_content: Some(HeaplessString::try_from("Automatic dormancy due to inactivity").unwrap()),
                l2_content: Some(HeaplessString::try_from("Dormance automatique due à l'inactivité").unwrap()),
                l3_content: Some(HeaplessString::try_from("Usingizi wa otomatiki kwa kutotumika").unwrap()),
                l1_language_code: Some(*b"eng"),
                l2_language_code: Some(*b"fra"),
                l3_language_code: Some(*b"swa"),
                requires_details: false,
                is_active: true,
                severity: Some(ReasonSeverity::Low),
                display_order: 1,
                compliance_metadata: None,
                created_at: Utc::now(),
                updated_at: Utc::now(),
                created_by_person_id: HeaplessString::try_from("system").unwrap(),
                updated_by_person_id: HeaplessString::try_from("system").unwrap(),
            },
        ]
    }
}